### PR TITLE
79 → 88

### PR DESCRIPTION
**Pull request by samcunliffe**
My reasons:

* black defaults to 88.
* Raymond H says "90 ish".
* By its nature, our app seems to get quite deeply indented.

```python
def get_callbacks(app: dash.Dash) -> None:
    @app.callback(
        [
            Output("beep", "boop"),
        ]
    )
    def flibble(blah: bool=True) -> None:
        if True:
            dash.Something(
                 arg="Hello",
                 arg2="Goodbye"
            )
```

The first commit makes the change, the second commit is linting. To minimise disruption, this should go in at a quiet moment.

## Dependencies

* A quiet moment.
    - [x] wait for a quiet moment.

### CODE REVIEW

**Comment by niksirbi** [comment]
Who is Raymond H.?

**Comment by samcunliffe** [comment]
> Who is Raymond H.?

Python core dev and one who is [wise about "foolish consistencies" and "hobgoblins"](https://www.youtube.com/watch?v=wf-BqAjZb8M). 😂

**Comment by samcunliffe** [comment]
Merge last!

**Review by niksirbi — APPROVED** [review]
From my side, feel free to merge this whenever you wish @samcunliffe

**Pull request merged**
