### PR TITLE
#12 exploring options to handle video metadata with json files

### PR DESCRIPTION
**Pull request by sfmig**
A draft PR with some thoughts about video metadata using json files

The aim of this draft PR is mainly to start a discussion on using json files (or equivalent) to record the videos metadata in the WAZP pipeline. I played around with a bit of code converting the csv data from Sanna's master-list into json files but no big developments.

Some aspects that I think would be useful to discuss:
- Should we have one json file per video (linked to the video by having the same filename), or one json file for all the metadata (in which the dictionary keys are the video filenames)? 
   - Any benefits of one over the other?
   - I find maybe one json per video is more user friendly but not sure
- Visualisation: also for user-friendliness, I think it would be nice to add a functionality to display the metadata associated to a video directory as a table. I played around with this option and it seems it can be easily done with pandas and Dash/Plotly.
- I envision the json file per video containing the following info:
   -  all the info in Sanna's masterlist
   - the ROIs defined per video. This would include a definition of the coordinate system
   - the event tagging info (frame number and tag)
- Where would these json files live? 
   - In a separate 'metadata' directory, parallel to the video directory? 
   - If one json file only, simply added to the video directory? (this may be the simplest)
- Are these metadata file(s) raw data?
   - strictly not raw, since they will be edited along the pipeline when adding ROIs or events
   - if we are strict about keeping raw and processed data separate, should we then move event tagging and ROIs definition to a different set of files? 
- From the perspective of the user: what happens when they upload a new video?
   - the way I see it right now is that the user would run a command to check which videos do not have metadata defined for them and then it would ask the user to fill in the data that currently lives in the master-list. Maybe we can use typer for this approach?
- In steps further down the pipeline, the following would be added to the metadata files: ROIs and coord system per video, and event tags.
- Also included in this PR, but probably worth a separate discussion: should we have a config file (also json?) to define the general pipeline?
   - this is imitating object detection/pose estimation pipelines 
   - it would contain parameters relevant to the overall project: video directory, model weights

### CODE REVIEW

**Comment by adamltyson** [comment]
Is it worth using something like YAML rather than JSON so that this metadata could, in principle, be edited directly by end users?

**Comment by samcunliffe** [comment]
> Should we have one json file per video (linked to the video by having the same filename)

I'd say yes. If we do a separate metadata file, it should be one per video... `fenraftspiderA_0.avi` ↔ `fenraftspiderA_0.metadata.{yml,json}`.

In the plus column for a simple YAML(JSON) file hanging out with the .avi in the same subdir, is that it's very obvious for a human what `fenraftspiderA_0.metadata.yml` contains. 

I do tend to prefer YAML for readability (less underscores and quotation marks). But I'm fine with [whatever is better for our use case](https://stackoverflow.com/questions/1726802/what-is-the-difference-between-yaml-and-json?answertab=votes#tab-top).

***

Naïve question also for @niksirbi Could we have YAML (or JSON) that _adheres_ to schema.org? Or is it more for embedding in the file itself somehow?

So then, matching Sanna's metadata fields to [schema/VideoObject](https://schema.org/VideoObject): I had a bit of a go, some are obvious. But a few might be difficult to sensibly map.

* Species name ↔ [Actor](https://schema.org/actor).
* Common name ?
* Subject ↔ [About](https://schema.org/about)
* Treatment ?
* Treatment description ?
* Start/end date/time ↔ [startTime](https://schema.org/startTime)/[endTime](https://schema.org/endTime) (both are datetime)
* Time recorded (not sure what this is) ↔ [uploadDate](https://schema.org/uploadDate)??
* Video length ↔ [Duration](https://schema.org/duration)
* Hardware description ?
* Software description ?
* Further description ↔ [Description](https://schema.org/description)

**Comment by samcunliffe** [comment]
There is a ready-made [pre-commit `check-yaml`](https://github.com/pre-commit/pre-commit-hooks#check-yaml) which could be tested here after rebasing onto #22 's merge commit.

**Comment by niksirbi** [comment]
> So then, matching Sanna's metadata fields to [schema/VideoObject](https://schema.org/VideoObject): I had a bit of a go, some are obvious. But a few might be difficult to sensibly map.
>     * Species name left_right_arrow [Actor](https://schema.org/actor).
>     * Common name?
>     * Subject left_right_arrow [About](https://schema.org/about)
>     * Treatment?
>     * Treatment description?
>     * Start/end date/time [startTime](https://schema.org/startTime)/[endTime](https://schema.org/endTime) (both are datetime)
>     * Time recorded (not sure what this is) left_right_arrow [uploadDate](https://schema.org/uploadDate)??
>     * Video length left_right_arrow [Duration](https://schema.org/duration)
>     * Hardware description?
>     * Software description?
>     * Further description [Description](https://schema.org/description)
>     * ROI definitions ?

The `VideoObject` instance of schema.org is under [Thing](https://schema.org/Thing) > [CreativeWork](https://schema.org/CreativeWork) > [MediaObject](https://schema.org/MediaObject) > [VideoObject](https://schema.org/VideoObject). As far as I understand, the properties of the parent classes are also available to us, not only the `VideoObject` properties.

Moreover, we may use the [Clip object](https://schema.org/Clip) from [Thing](https://schema.org/Thing "Thing") > [CreativeWork](https://schema.org/CreativeWork "CreativeWork") > [Clip](https://schema.org/Clip "Clip") This might be particularly useful for defining specific segment of the video for analysis or particular events in the video. 

Below I've listed all properties that might be useful for us either immediately or more long-term in the Zoo project.  I have highlighted in **bold** the ones that may directly correspond to metadata fields in the master xlsx. 

## Thing
* **name: Text -> can be the name of the video/clip/event (currently "File" in master xlsx)**
* alternateName: Text -> We can store an optional alias name here, unsure if usefule
* description: Text -> may be useful for sth like "Hardware/Software descriptions" or "further description" or not (see "comment" property below)
* identifier: Text -> we could add a unique identifier to each video/clip, maybe a hash?

## CreativeWork
* creator: Organization/Person -> this can be the experimenter or team of experimenters
* sourceOrganization: Organization -> SWC/LondonZoo
* contributor: Orgnaization/Person -> other people/teams involved in the project
* locationCreated: Place -> this can be the Zoo or the specific enclosure
* dateCreated: Date/DateTime -> can be useful
* dateModified: Date/DateTime -> can be useful
* isPartOf: CreativeWork -> can be useful when we have 1 video split into parts
* hasPart: CreativeWork -> same use-case as above
* abstract: Text -> 
* character: Person -> this usually means fictional person shown in video, unsure if it's useful for us
* **comment: Comment -> this is normally used for user comments under videos/blogposts but we could potentially use it for storing the various description fields. We could use the "about" property of the [Comment object](https://schema.org/Comment) to indicate what it describes (e.g. "Hardware", "Software", "Treatment", "Further"). We could incorporate any number of comment fields this way?**

## MediaObject
* bitrate: Text -> I can imagine this being potentially useful
* contentSize: Text -> File size in megabytes
* **duration: Duration -> "Video length" from master xlsx**
* encodingFormat: Text -> Video encoding format
* **endTime: DateTime/Time -> "Date/Time end" from master xlsx**
* **startTime: DateTime/Time -> "Date/Time start" from master xlsx**
* uploadDate: Date -> could be the date uploaded to ceph (probably hard to implement and unnecessary)
* width: Distance or QuantitativeValue -> frame width?
* height: Distance or QuantitativeValue -> frame height?

## VideoObject
* **actor: Person -> "Subject" from the master xlsx (have to decide what to do for future videos with multiple subjects)**
* videoFrameSize: Text -> could be useful
* videoQuality: Text -> could be useful if the experimenter uses some defined QA metric (e.g. A/B/C)

## Clip
* clipNumber: Integer -> Position of the clip within an ordered group of clips
* startOffset: Number -> The start time of the clip expressed as sec/ms from the beginning. When used without endOffset, may be used to define the timestamp of a specific event
* endOffset: Number -> The end time of the clip expressed as sec/ms from the beginning. In combination with startOffset, can be used to defined a specific video segment.

## Non-schema objects/properties we should probably add
schema.org defines a Person object, we could in principle define our own custom "Animal" object, with the following properties:
* speciesName: Text
* commonName: Text
* sex: Text (F/M)
* age? (not useful here but in future)
* bodyweight? (not useful here but in future)
* subject? (if we don't use the "actor" property, if we define a separate "sex" property, this could become just an alphabetical capital letter)

## Issues unresolved by the above plan
* I still don't know what to do with the "Treatment" field
* I am not happy with shoving all description fields as comments, we might be better of defining custom properties of the VideoObject, e.g.:
    * hardware: string or list of strings
    * software: string or list of strings
    * treatment: string or list of strings
    * notes: string or list of strings (essentially the "further comments" field

**Comment by niksirbi** [comment]
> * ROI definitions ?

For ROIs, I strongly recommend doing it like in [napari's shapes layer](https://napari.org/stable/howtos/layers/shapes.html). It allows you to create any arbitrary line or polygon, and uses a standardized way of saving the shapes into a `.csv` file. Added bonus: new versions of deeplabcut use the [napari points layer](https://napari.org/stable/howtos/layers/points.html) to annotate animal body parts, and therefore points (body parts) and shapes (ROIs) will be in the same coordinate system by default.
In the future, we might even think about using the [tracks layer of napari](https://napari.org/stable/howtos/layers/tracks.html) for visualising animal trajectories. This way we will be aligned with an actively developed, well-supported ecosystem.

**Comment by niksirbi** [comment]
Because I am beginning to realise that adapting schema.org for our purposes may be too much work, I have also proposed an alternative - completely different - idea for handling metadata in issue #12

**Comment by sfmig** [comment]
thanks @niksirbi for having a look at this. My impression is also that adapting to schema may be a bit overkill for our case and I don't see a clear advantage over using yaml config files, but happy to discuss further during the standup.

**Pull request closed without merging**
